### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by OpakAlex** [Kinvey/ember-cli-fontcustom#3]
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn fontcustom ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
    at child_process.js:1137:20
    at process._tickCallback (node.js:355:11)

node: 12.0

What is this?

**Comment by davewasmer** [comment]
@OpakAlex looks like you don't have fontcustom installed. You'll need to install it first. Check out the [installation guide on the fontcustom repo](https://github.com/FontCustom/fontcustom#installation).

**Comment by davewasmer** [comment]
I'm closing this for now, but if the issue persists even after you've installed fontcustom, feel free to comment here and I'll reopen.

**Comment by narayananvenkat** [comment]
after installing also I got the same issue.
